/* AUTO-GENERATED FILE. DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found. It
 * should not be modified by hand.
 */

package com.user.anypair;

public final class R {
  public static final class drawable {
    public static final int bg_button=0x7f010000;
    public static final int bg_card=0x7f010001;
    public static final int bg_icon_card=0x7f010002;
    public static final int bg_input=0x7f010003;
    public static final int bg_popup=0x7f010004;
    public static final int genericbuds=0x7f010005;
    public static final int ic_background=0x7f010006;
    public static final int ic_charge=0x7f010007;
    public static final int ic_close=0x7f010008;
    public static final int ic_settings=0x7f010009;
  }
  public static final class id {
    public static final int btn_close=0x7f020000;
    public static final int btn_comenzar=0x7f020001;
    public static final int btn_guardar=0x7f020002;
    public static final int btn_permiso_overlay=0x7f020003;
    public static final int btn_permisos=0x7f020004;
    public static final int btn_seleccionar_imagen=0x7f020005;
    public static final int btn_settings=0x7f020006;
    public static final int btn_test=0x7f020007;
    public static final int btn_x=0x7f020008;
    public static final int et_boton=0x7f020009;
    public static final int et_nombre=0x7f02000a;
    public static final int et_subtitulo=0x7f02000b;
    public static final int img_audifonos=0x7f02000c;
    public static final int img_preview=0x7f02000d;
    public static final int rb_3s=0x7f02000e;
    public static final int rb_7s=0x7f02000f;
    public static final int rb_inf=0x7f020010;
    public static final int rg_tiempo=0x7f020011;
    public static final int sw_blur=0x7f020012;
    public static final int tv_subtitle=0x7f020013;
    public static final int tv_title=0x7f020014;
  }
  public static final class layout {
    public static final int activity_main=0x7f030000;
    public static final int activity_onboarding=0x7f030001;
    public static final int activity_settings=0x7f030002;
    public static final int popup=0x7f030003;
  }
  public static final class mipmap {
    public static final int ic_launcher=0x7f040000;
    public static final int ic_launcher_adaptive_back=0x7f040001;
    public static final int ic_launcher_adaptive_fore=0x7f040002;
    public static final int icon_foreground=0x7f040003;
  }
  public static final class style {
    public static final int Theme_AnyPair=0x7f050000;
  }
}